# Generated by Django 5.2.11 on 2026-02-16 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-date']},
        ),
    ]
