# Generated by Django 5.2.11 on 2026-02-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_activity_options_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='co2_factor',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
