# Generated by Django 5.2.11 on 2026-02-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_alter_category_co2_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='unit',
            field=models.CharField(choices=[('km', 'Kilometers (km)'), ('kg', 'Kilograms (kg)'), ('kWh', 'Kilowatt-hours (kWh)'), ('l', 'Liters (l)'), ('h', 'Hours (h)')], default='km', max_length=10),
        ),
    ]
